---
name: Prettier

on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
    run:
        name: Can the code be prettier? 🤔
        runs-on: ubuntu-latest
        # workflow_dispatch always lets you select the branch ref, even though in this case we only ever want to run the action on `main` this we need an if check
        if: ${{ github.ref_name == 'main' }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: yarn
                  node-version: lts/*
            - run: yarn install --frozen-lockfile --ignore-scripts
            - uses: actions/cache@v3
              with:
                  path: node_modules/.cache/prettier/.prettier-cache
                  key: prettier-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.gitignore') }}
            - run: npx prettier --ignore-path .gitignore --cache --write .
            - run: git restore .github/workflows
